# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-03-20 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='action',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='action2',
            field=models.NullBooleanField(),
        ),
    ]
