# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-03-20 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190319_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
