# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-03-27 01:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190326_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 27, 1, 14, 35, 410247, tzinfo=utc)),
        ),
    ]
