# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-03-27 01:33
from __future__ import unicode_literals

import blog.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190326_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 27, 1, 33, 10, 924685, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='publish_email',
            field=models.CharField(max_length=240, null=True, validators=[blog.models.publish_email_validation, blog.models.check_string_validation]),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Post Title'),
        ),
    ]
