# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-03-27 01:46
from __future__ import unicode_literals

import blog.validators
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190326_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='email',
            field=models.EmailField(max_length=240, null=True, validators=[blog.validators.check_string_validation]),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 27, 1, 46, 44, 771495, tzinfo=utc)),
        ),
    ]
