# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-03-30 23:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20190330_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2019, 3, 30, 23, 41, 51, 994111, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(error_messages={'unique': 'This title is not unique'}, help_text='This item should be unique.', max_length=200, null=True, unique=True, verbose_name='Post Title'),
        ),
    ]
