# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-04-02 04:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.manager
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20190330_2032'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='postmodel',
            managers=[
                ('modManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 2, 4, 42, 3, 447170, tzinfo=utc)),
        ),
    ]
